### ISSUE TITLE
Audio y tiempo en win/loose

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_tools#4]
- creo que el audio de win deberia ponerse en el intervalo de espera para mantener al usuario entretenido
- tiempo de espera del win muy largo, probar con 2 segundos
- por que en el loose no hay tiempo de espera?
- valorar la posibilidad de el intervalo de espera sea mas claro, como con un popup que diga ganastes o algo asi

**Comment by Aidyl98** [comment]
```dart
async {
    StrawberryAudio.playAudioLose();
    // Time before push one page above other.
    await Future.delayed(timeBeforeTheTransition);
}
```
